version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: werikoliveira/dphoto:latest
    container_name: dphoto-app
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
