name: dphoto

services:
  app:
    image: werikoliveira/dphoto:latest
    container_name: dphoto-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - APP_NAME=DPhoto
      - APP_URL=http://localhost:3000
    volumes:
      - ./data:/app/data

x-casaos:
  main: app
  title:
    en_us: DPhoto Pro
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/camera.png
  port_map: "3000"
